#!/usr/bin/env python3
"""Validate AI digest JSON and report it to backend API."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import ssl
import sys
import urllib.error
import urllib.parse
import urllib.request
from typing import Any
from zoneinfo import ZoneInfo

DEFAULT_BASE_URL = "https://api.aitrend.us"
DEFAULT_SITE_BASE_URL = "https://www.aitrend.us"
DEFAULT_REPORT_TOKEN = "baogaoai-agent-static-token-2026"
TARGET_TZ = ZoneInfo("Asia/Shanghai")
RE_CJK = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff]")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate and report digest payload generated by AI.")
    parser.add_argument("--input", required=True)
    parser.add_argument("--context")
    parser.add_argument("--digest-date")
    parser.add_argument("--run-at")
    parser.add_argument("--ai-model", default="agent-model")
    parser.add_argument("--ai-call-count", type=int, default=1)
    parser.add_argument("--token", default=DEFAULT_REPORT_TOKEN)
    parser.add_argument("--base-url", default=DEFAULT_BASE_URL)
    parser.add_argument("--site-base-url", default=DEFAULT_SITE_BASE_URL)
    parser.add_argument("--timeout", type=float, default=20.0)
    parser.add_argument("--payload-out")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--skip-page-verify", action="store_true")
    parser.add_argument("--insecure", action="store_true")
    return parser.parse_args()


def load_json(path: str) -> Any:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_json(path: str, payload: dict[str, Any]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
        f.write("\n")


def normalize_id(value: Any) -> int | str:
    if isinstance(value, bool):
        raise ValueError("ID cannot be boolean")
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        stripped = value.strip()
        if not stripped:
            raise ValueError("ID cannot be empty")
        if stripped.isdigit():
            return int(stripped)
        return stripped
    if value is None:
        raise ValueError("ID cannot be null")
    return str(value)


def unique_ids(values: list[Any]) -> list[int | str]:
    out: list[int | str] = []
    seen: set[str] = set()
    for raw in values:
        v = normalize_id(raw)
        key = str(v)
        if key in seen:
            continue
        seen.add(key)
        out.append(v)
    return out


def has_chinese(text: str) -> bool:
    return bool(RE_CJK.search(text))


def require_string(name: str, value: Any, require_chinese: bool = False) -> str:
    if not isinstance(value, str):
        raise ValueError(f"{name} must be a string")
    trimmed = value.strip()
    if not trimmed:
        raise ValueError(f"{name} cannot be empty")
    if require_chinese and not has_chinese(trimmed):
        raise ValueError(f"{name} must contain Chinese text")
    return trimmed


def locate_digest_block(payload: Any) -> dict[str, Any]:
    if isinstance(payload, dict):
        if "contentHtml" in payload and "title" in payload:
            return payload
        for key in ("digest", "output", "result", "data", "report"):
            nested = payload.get(key)
            if isinstance(nested, dict) and "contentHtml" in nested:
                return nested
    raise ValueError("Cannot find digest block. Expected 'contentHtml' and 'title'.")


def parse_date_or_default(explicit_date, context):
    if explicit_date:
        try:
            return dt.date.fromisoformat(explicit_date).isoformat()
        except ValueError as exc:
            raise ValueError("--digest-date must be YYYY-MM-DD") from exc
    if context and isinstance(context.get("targetDate"), str):
        try:
            return dt.date.fromisoformat(context["targetDate"]).isoformat()
        except ValueError:
            pass
    return dt.datetime.now(TARGET_TZ).date().isoformat()


def parse_run_at(value):
    if not value:
        return dt.datetime.now(TARGET_TZ).replace(microsecond=0).isoformat()
    raw = value.strip()
    try:
        normalized = raw.replace("Z", "+00:00")
        parsed = dt.datetime.fromisoformat(normalized)
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=TARGET_TZ)
        return parsed.astimezone(TARGET_TZ).replace(microsecond=0).isoformat()
    except ValueError as exc:
        raise ValueError("--run-at must be ISO 8601 timestamp") from exc


def build_payload(ai_output, context, args):
    if context and str(context.get("status", "")).lower() == "skip":
        raise ValueError("Context indicates skip status; do not report digest for this date.")
    digest_block = locate_digest_block(ai_output)
    title = require_string("title", digest_block.get("title"), require_chinese=True)
    summary = require_string("summary", digest_block.get("summary"), require_chinese=True)
    content_html = require_string("contentHtml", digest_block.get("contentHtml"), require_chinese=True)
    source_ids_raw = digest_block.get("sourceArticleIds", [])
    if not source_ids_raw and context:
        source_ids_raw = context.get("sourceArticleIds", [])
    source_ids = unique_ids(source_ids_raw)
    digest_date = parse_date_or_default(args.digest_date, context)
    run_at = parse_run_at(args.run_at)
    if args.ai_call_count <= 0:
        raise ValueError("--ai-call-count must be > 0")
    return {
        "digestDate": digest_date,
        "runAt": run_at,
        "articleCount": len(source_ids),
        "aiModel": args.ai_model,
        "aiCallCount": args.ai_call_count,
        "title": title,
        "summary": summary,
        "contentHtml": content_html,
        "sourceArticleIds": source_ids,
    }


def ssl_context(insecure):
    if insecure:
        return ssl._create_unverified_context()
    return None


def post_json(url, payload, token, timeout, insecure):
    data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    req = urllib.request.Request(
        url,
        method="POST",
        data=data,
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
            "Accept": "application/json",
            "User-Agent": "baogaoai-ai-digest-generator/1.0",
        },
    )
    with urllib.request.urlopen(req, timeout=timeout, context=ssl_context(insecure)) as response:
        raw = response.read().decode("utf-8")
        if not raw.strip():
            return {"status": "ok"}
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            return {"raw": raw}


def get_json(url, timeout, insecure):
    req = urllib.request.Request(
        url,
        headers={"Accept": "application/json", "User-Agent": "baogaoai-ai-digest-generator/1.0"},
    )
    with urllib.request.urlopen(req, timeout=timeout, context=ssl_context(insecure)) as response:
        raw = response.read().decode("utf-8")
    return json.loads(raw)


def verify_page(url, timeout, insecure):
    req = urllib.request.Request(
        url,
        method="GET",
        headers={"User-Agent": "baogaoai-ai-digest-generator/1.0"},
    )
    with urllib.request.urlopen(req, timeout=timeout, context=ssl_context(insecure)) as response:
        return getattr(response, "status", 200)


def main() -> int:
    args = parse_args()
    try:
        ai_output = load_json(args.input)
        context = load_json(args.context) if args.context else None
        payload = build_payload(ai_output, context, args)
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(f"Validation failed: {exc}", file=sys.stderr)
        return 1

    if args.payload_out:
        save_json(args.payload_out, payload)

    if args.dry_run:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return 0

    if not args.token:
        print("Missing token. Pass --token.", file=sys.stderr)
        return 1

    report_url = f"{args.base_url.rstrip('/')}/admin/digest/report"
    verify_api_url = f"{args.base_url.rstrip('/')}/digest?{urllib.parse.urlencode({'date': payload['digestDate']})}"
    verify_page_url = f"{args.site_base_url.rstrip('/')}/digest/{payload['digestDate']}"

    try:
        report_response = post_json(report_url, payload, args.token, args.timeout, args.insecure)
        api_verify_response = get_json(verify_api_url, args.timeout, args.insecure)
        page_status = None
        if not args.skip_page_verify:
            page_status = verify_page(verify_page_url, args.timeout, args.insecure)
    except (urllib.error.URLError, json.JSONDecodeError) as exc:
        print(f"Report/verify failed: {exc}", file=sys.stderr)
        return 1

    summary = {
        "status": "ok",
        "reportUrl": report_url,
        "verifyApiUrl": verify_api_url,
        "verifyPageUrl": None if args.skip_page_verify else verify_page_url,
        "verifyPageStatus": page_status,
        "reportResponse": report_response,
        "verifyApiResponse": api_verify_response,
    }
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
