/**
 * Codex CLI Adapter
 *
 * Integrates OpenAI Codex CLI with the Antigravity Gateway via two execution modes:
 *
 *   1. exec mode  — `codex exec` (non-interactive, one-shot task)
 *   2. MCP mode   — `codex mcp-server` (multi-turn sessions via MCP protocol)
 *
 * Official docs: https://developers.openai.com/codex/guides/agents-sdk
 */

import { spawn, type ChildProcess } from 'child_process';
import { createLogger } from '../logger';

const log = createLogger('CodexAdapter');

// ─── Types ──────────────────────────────────────────────────────────────────

export type CodexSandbox = 'read-only' | 'workspace-write' | 'danger-full-access';
export type CodexApprovalPolicy = 'untrusted' | 'on-request' | 'never';

export interface CodexExecOptions {
  /** Working directory for the Codex session. */
  cwd?: string;
  /** Override the model (e.g. `o3`, `o4-mini`). */
  model?: string;
  /** Sandbox mode. Defaults to `read-only`. */
  sandbox?: CodexSandbox;
  /** Whether to emit JSON Lines (JSONL) on stdout. */
  json?: boolean;
  /** Maximum milliseconds to wait before aborting. 0 = no limit. */
  timeoutMs?: number;
}

export interface CodexMCPSessionOptions {
  /** Working directory for the Codex session. */
  cwd?: string;
  /** Override the model. */
  model?: string;
  /** Sandbox mode. Defaults to `workspace-write`. */
  sandbox?: CodexSandbox;
  /** Approval policy for shell commands generated by the model. Defaults to `never` (full-auto). */
  approvalPolicy?: CodexApprovalPolicy;
  /** Replace the default Codex instructions with this string. */
  baseInstructions?: string;
}

/** Structured content returned by both `codex` and `codex-reply` MCP tools. */
export interface CodexMCPResult {
  threadId: string;
  content: string;
}

// ─── MCP protocol helpers ────────────────────────────────────────────────────

interface JsonRpcRequest {
  jsonrpc: '2.0';
  id: number;
  method: string;
  params?: unknown;
}

interface JsonRpcNotification {
  jsonrpc: '2.0';
  method: string;
  params?: unknown;
}

interface JsonRpcResponse {
  jsonrpc: '2.0';
  id: number;
  result?: unknown;
  error?: { code: number; message: string; data?: unknown };
}

// ─── Codex MCP Client ────────────────────────────────────────────────────────

/**
 * Thin MCP client that speaks to a `codex mcp-server` child process.
 *
 * Transport: newline-delimited JSON (NDJSON) over stdin/stdout, per MCP spec.
 */
export class CodexMCPClient {
  private proc: ChildProcess | null = null;
  private pending = new Map<number, { resolve: (v: unknown) => void; reject: (e: Error) => void }>();
  private nextId = 1;
  private readBuf = '';
  private ready = false;

  async start(cwd?: string): Promise<void> {
    if (this.ready) return;

    const env: NodeJS.ProcessEnv = {
      ...process.env,
      // Allow caller to supply an OpenAI API key via the environment.
      ...(process.env.CODEX_API_KEY ? {} : {
        CODEX_API_KEY: process.env.OPENAI_API_KEY ?? '',
      }),
    };

    this.proc = spawn('codex', ['mcp-server'], {
      cwd,
      stdio: ['pipe', 'pipe', 'pipe'],
      env,
    });

    this.proc.stderr?.on('data', (chunk: Buffer) => {
      log.debug({ msg: chunk.toString().trim() }, 'codex mcp-server stderr');
    });

    this.proc.stdout!.on('data', (chunk: Buffer) => {
      this.readBuf += chunk.toString();
      let nl: number;
      while ((nl = this.readBuf.indexOf('\n')) !== -1) {
        const line = this.readBuf.slice(0, nl).trim();
        this.readBuf = this.readBuf.slice(nl + 1);
        if (line) this.handleMessage(line);
      }
    });

    this.proc.on('error', (err) => {
      log.error({ err }, 'codex mcp-server process error');
      for (const { reject } of this.pending.values()) reject(err);
      this.pending.clear();
    });

    this.proc.on('close', (code) => {
      log.info({ code }, 'codex mcp-server exited');
      const err = new Error(`codex mcp-server exited with code ${code}`);
      for (const { reject } of this.pending.values()) reject(err);
      this.pending.clear();
      this.ready = false;
    });

    // --- MCP handshake ---
    await this.request('initialize', {
      protocolVersion: '2024-11-05',
      capabilities: {},
      clientInfo: { name: 'antigravity-gateway', version: '1.0.0' },
    });
    this.notify('notifications/initialized', {});
    this.ready = true;
    log.info('CodexMCPClient ready');
  }

  /** Stop the Codex MCP server process. */
  stop(): void {
    this.ready = false;
    this.proc?.kill();
    this.proc = null;
  }

  /** Return the list of MCP tools advertised by the server. */
  async listTools(): Promise<unknown[]> {
    const res = (await this.request('tools/list', {})) as { tools?: unknown[] };
    return res.tools ?? [];
  }

  /**
   * Start a new Codex session.
   * Calls the `codex` MCP tool and returns `{ threadId, content }`.
   */
  async startSession(prompt: string, opts: CodexMCPSessionOptions = {}): Promise<CodexMCPResult> {
    return this.callTool('codex', {
      prompt,
      ...(opts.cwd ? { cwd: opts.cwd } : {}),
      ...(opts.model ? { model: opts.model } : {}),
      ...(opts.sandbox ? { sandbox: opts.sandbox } : {}),
      ...(opts.approvalPolicy ? { 'approval-policy': opts.approvalPolicy } : {}),
      ...(opts.baseInstructions ? { 'base-instructions': opts.baseInstructions } : {}),
    });
  }

  /**
   * Continue an existing Codex session by thread ID.
   * Calls the `codex-reply` MCP tool.
   */
  async reply(threadId: string, prompt: string): Promise<CodexMCPResult> {
    return this.callTool('codex-reply', { threadId, prompt });
  }

  // --- private helpers ---

  private handleMessage(line: string): void {
    let msg: JsonRpcResponse;
    try {
      msg = JSON.parse(line);
    } catch {
      log.warn({ line }, 'Ignoring unparseable message from codex mcp-server');
      return;
    }

    const pending = this.pending.get(msg.id);
    if (!pending) return;
    this.pending.delete(msg.id);

    if (msg.error) {
      pending.reject(new Error(`MCP error ${msg.error.code}: ${msg.error.message}`));
    } else {
      pending.resolve(msg.result);
    }
  }

  private request(method: string, params: unknown): Promise<unknown> {
    return new Promise((resolve, reject) => {
      const id = this.nextId++;
      this.pending.set(id, { resolve, reject });
      const msg: JsonRpcRequest = { jsonrpc: '2.0', id, method, params };
      this.write(msg);
    });
  }

  private notify(method: string, params: unknown): void {
    const msg: JsonRpcNotification = { jsonrpc: '2.0', method, params };
    this.write(msg);
  }

  private write(msg: object): void {
    if (!this.proc?.stdin?.writable) {
      throw new Error('CodexMCPClient: process stdin is not writable');
    }
    this.proc.stdin.write(JSON.stringify(msg) + '\n');
  }

  private async callTool(name: string, args: Record<string, unknown>): Promise<CodexMCPResult> {
    if (!this.ready) throw new Error('CodexMCPClient not started — call start() first');

    const res = (await this.request('tools/call', {
      name,
      arguments: args,
    })) as {
      structuredContent?: { threadId: string; content: string };
      content?: Array<{ type: string; text: string }>;
    };

    // Prefer structuredContent (MCP modern clients)
    if (res.structuredContent?.threadId) {
      return res.structuredContent;
    }

    // Fallback: extract from legacy content array
    const text = res.content?.find((c) => c.type === 'text')?.text ?? '';
    // threadId may be absent in legacy responses; callers should treat '' as unknown.
    return { threadId: '', content: text };
  }
}

// ─── One-shot exec wrapper ───────────────────────────────────────────────────

/**
 * Run `codex exec` in a subprocess for a single non-interactive task.
 *
 * stdout is the final agent message; stderr is progress output.
 * Returns the final text output from Codex.
 */
export async function codexExec(
  prompt: string,
  opts: CodexExecOptions = {},
): Promise<string> {
  const {
    cwd,
    model,
    sandbox = 'read-only',
    json = false,
    timeoutMs = 0,
  } = opts;

  const args: string[] = ['exec'];
  if (sandbox === 'workspace-write' || sandbox === 'danger-full-access') {
    args.push('--full-auto');
  }
  if (sandbox !== 'read-only') {
    args.push('--sandbox', sandbox);
  }
  if (model) args.push('--model', model);
  if (json) args.push('--json');
  args.push(prompt);

  return new Promise((resolve, reject) => {
    const env: NodeJS.ProcessEnv = {
      ...process.env,
      ...(process.env.CODEX_API_KEY ? {} : {
        CODEX_API_KEY: process.env.OPENAI_API_KEY ?? '',
      }),
    };

    const proc = spawn('codex', args, {
      cwd,
      stdio: ['ignore', 'pipe', 'pipe'],
      env,
    });

    let stdout = '';
    let stderr = '';

    proc.stdout.on('data', (d: Buffer) => { stdout += d.toString(); });
    proc.stderr.on('data', (d: Buffer) => { stderr += d.toString(); });

    let timer: ReturnType<typeof setTimeout> | null = null;
    if (timeoutMs > 0) {
      timer = setTimeout(() => {
        proc.kill();
        reject(new Error(`codex exec timed out after ${timeoutMs}ms`));
      }, timeoutMs);
    }

    proc.on('error', (err) => {
      if (timer) clearTimeout(timer);
      reject(err);
    });

    proc.on('close', (code) => {
      if (timer) clearTimeout(timer);
      if (code !== 0) {
        reject(new Error(`codex exec exited with code ${code}. stderr: ${stderr.slice(0, 500)}`));
      } else {
        resolve(stdout.trim());
      }
    });
  });
}

// ─── Availability check ──────────────────────────────────────────────────────

/** Return true if the `codex` binary is reachable via PATH. */
export async function isCodexAvailable(): Promise<boolean> {
  return new Promise((resolve) => {
    const proc = spawn('codex', ['--version'], { stdio: 'ignore' });
    proc.on('error', () => resolve(false));
    proc.on('close', (code) => resolve(code === 0));
  });
}
