import { createHash } from 'crypto';
import fs from 'fs';
import path from 'path';

import type {
  EvidenceRef,
  SystemImprovementArea,
  SystemImprovementSignal,
  SystemImprovementSeverity,
} from './contracts';
import { getSystemImprovementSignal, listSystemImprovementSignals, upsertSystemImprovementSignal } from './self-improvement-store';
import { createSystemImprovementSignal } from './self-improvement-signal';
import {
  isActiveStoryTopCandidateMetadata,
  isStoryTopCandidateMetadata,
  STORY_TOP_CANDIDATE_ARTIFACT,
  STORY_TOP_CANDIDATE_KIND,
  type StoryTopCandidateArea,
  type StoryTopCandidateMetadata,
  type StoryTopCandidatePayload,
  type StoryTopCandidateSeverity,
} from '../story-top-candidates';

const MAX_TOP_CANDIDATES = 3;

const VALID_AREAS = new Set<SystemImprovementArea>([
  'frontend',
  'api',
  'runtime',
  'scheduler',
  'provider',
  'knowledge',
  'approval',
  'database',
  'docs',
]);

const VALID_SEVERITIES = new Set<SystemImprovementSeverity>(['low', 'medium', 'high', 'critical']);

function shaSuffix(input: string): string {
  return createHash('sha1').update(input).digest('hex').slice(0, 16);
}

function normalizeStoryTopSourcePath(value: string): string {
  return value.replace(/\\/g, '/').replace(/^\/+/, '').trim();
}

function resolveStoryKey(candidate: StoryTopCandidatePayload): string {
  const explicit = typeof candidate.storyKey === 'string' ? candidate.storyKey.trim() : '';
  if (explicit) return explicit;
  return shaSuffix(`${normalizeStoryTopSourcePath(candidate.sourcePath)}\n${candidate.storyText.trim()}`);
}

function toSignalId(storyKey: string): string {
  return `system-improvement-signal:story-top:${storyKey}`;
}

function normalizeCandidateSeverity(value: unknown): StoryTopCandidateSeverity {
  return typeof value === 'string' && VALID_SEVERITIES.has(value as SystemImprovementSeverity)
    ? value as StoryTopCandidateSeverity
    : 'high';
}

function inferAreasFromSourcePath(sourcePath: string): SystemImprovementArea[] {
  const normalized = normalizeStoryTopSourcePath(sourcePath);
  if (normalized.includes('Knowledge/')) return ['knowledge', 'frontend'];
  if (normalized.includes('Ops/')) return ['scheduler', 'runtime'];
  if (normalized.includes('Settings/')) return ['provider', 'approval', 'runtime'];
  if (normalized.includes('Projects/')) return ['frontend', 'runtime'];
  if (normalized.includes('CEO Office/')) return ['frontend', 'runtime'];
  return ['docs'];
}

function normalizeCandidateAreas(value: unknown, sourcePath: string): SystemImprovementArea[] {
  if (Array.isArray(value)) {
    const areas = value.filter((item): item is SystemImprovementArea =>
      typeof item === 'string' && VALID_AREAS.has(item as SystemImprovementArea));
    if (areas.length) {
      return Array.from(new Set(areas));
    }
  }
  return inferAreasFromSourcePath(sourcePath);
}

function normalizeCandidateRecord(value: unknown): StoryTopCandidatePayload | null {
  if (!value || typeof value !== 'object') return null;
  const record = value as Record<string, unknown>;
  const sourcePath = typeof record.sourcePath === 'string' ? normalizeStoryTopSourcePath(record.sourcePath) : '';
  const storyText = typeof record.storyText === 'string' ? record.storyText.trim() : '';
  const title = typeof record.title === 'string' ? record.title.trim() : '';
  const summary = typeof record.summary === 'string' ? record.summary.trim() : '';
  const expectedOutcome = typeof record.expectedOutcome === 'string' ? record.expectedOutcome.trim() : '';
  const rationale = typeof record.rationale === 'string' ? record.rationale.trim() : '';
  if (!sourcePath || !storyText || !title || !summary || !expectedOutcome || !rationale) {
    return null;
  }
  return {
    ...(typeof record.storyKey === 'string' && record.storyKey.trim() ? { storyKey: record.storyKey.trim() } : {}),
    sourcePath,
    storyText,
    title,
    summary,
    expectedOutcome,
    severity: normalizeCandidateSeverity(record.severity),
    rationale,
    affectedAreas: normalizeCandidateAreas(record.affectedAreas, sourcePath) as StoryTopCandidateArea[],
  };
}

function buildStoryTopEvidence(workspacePath: string, candidate: StoryTopCandidatePayload, createdAt: string): EvidenceRef {
  const normalizedPath = normalizeStoryTopSourcePath(candidate.sourcePath);
  return {
    id: `evidence:story-top:${resolveStoryKey(candidate)}`,
    type: 'file',
    label: 'User Story candidate source',
    filePath: path.join(workspacePath, normalizedPath),
    excerpt: candidate.storyText,
    createdAt,
  };
}

function buildCandidateMetadata(existing: SystemImprovementSignal | null, candidate: StoryTopCandidatePayload, input: {
  batchId: string;
  generatedAt: string;
  workspaceUri: string;
}): StoryTopCandidateMetadata {
  const storyKey = resolveStoryKey(candidate);
  return {
    ...((existing?.metadata || {}) as StoryTopCandidateMetadata),
    autoGeneratedBy: 'platform-engineering-story-top-candidate-daily',
    departmentId: 'department:platform-engineering',
    workspaceUri: input.workspaceUri,
    candidateKind: STORY_TOP_CANDIDATE_KIND,
    candidateActive: true,
    storyKey,
    sourcePath: normalizeStoryTopSourcePath(candidate.sourcePath),
    storyText: candidate.storyText,
    expectedOutcome: candidate.expectedOutcome,
    rationale: candidate.rationale,
    candidateBatchId: input.batchId,
    candidateGeneratedAt: input.generatedAt,
  } as StoryTopCandidateMetadata;
}

export function isStoryTopCandidateSignal(signal: SystemImprovementSignal): boolean {
  return signal.source === 'user-story-gap' && isStoryTopCandidateMetadata(signal.metadata || undefined);
}

export function isActiveStoryTopCandidateSignal(signal: SystemImprovementSignal): boolean {
  return signal.source === 'user-story-gap' && isActiveStoryTopCandidateMetadata(signal.metadata || undefined);
}

function deactivateSignal(signal: SystemImprovementSignal, batchId: string, generatedAt: string): SystemImprovementSignal {
  return upsertSystemImprovementSignal({
    ...signal,
    metadata: {
      ...(signal.metadata || {}),
      candidateKind: STORY_TOP_CANDIDATE_KIND,
      candidateActive: false,
      candidateBatchId: batchId,
      candidateGeneratedAt: generatedAt,
    },
  });
}

export function ingestStoryTopCandidatesFromArtifact(input: {
  workspacePath: string;
  workspaceUri: string;
  artifactAbsDir: string;
}): { count: number; signals: SystemImprovementSignal[] } {
  const artifactPath = path.join(input.artifactAbsDir, STORY_TOP_CANDIDATE_ARTIFACT);
  if (!fs.existsSync(artifactPath)) {
    throw new Error(`${STORY_TOP_CANDIDATE_ARTIFACT} not found`);
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(fs.readFileSync(artifactPath, 'utf-8'));
  } catch {
    throw new Error(`${STORY_TOP_CANDIDATE_ARTIFACT} is not valid JSON`);
  }

  if (!Array.isArray(parsed)) {
    throw new Error(`${STORY_TOP_CANDIDATE_ARTIFACT} must be a JSON array`);
  }

  const generatedAt = new Date().toISOString();
  const batchId = path.basename(input.artifactAbsDir) || `story-top-${shaSuffix(generatedAt)}`;
  const candidates = parsed
    .map(normalizeCandidateRecord)
    .filter((candidate): candidate is StoryTopCandidatePayload => Boolean(candidate))
    .slice(0, MAX_TOP_CANDIDATES);

  if (candidates.length === 0) {
    throw new Error(`${STORY_TOP_CANDIDATE_ARTIFACT} did not contain any valid candidates`);
  }

  const activeSignalIds = new Set<string>();
  const storedSignals: SystemImprovementSignal[] = [];

  for (const candidate of candidates) {
    const storyKey = resolveStoryKey(candidate);
    const signalId = toSignalId(storyKey);
    activeSignalIds.add(signalId);
    const existing = getSystemImprovementSignal(signalId);
    const stored = createSystemImprovementSignal({
      id: signalId,
      source: 'user-story-gap',
      title: candidate.title,
      summary: candidate.summary,
      evidenceRefs: [buildStoryTopEvidence(input.workspacePath, candidate, generatedAt)],
      affectedAreas: normalizeCandidateAreas(candidate.affectedAreas, candidate.sourcePath),
      severity: normalizeCandidateSeverity(candidate.severity),
      recurrence: 1,
      metadata: buildCandidateMetadata(existing, candidate, {
        batchId,
        generatedAt,
        workspaceUri: input.workspaceUri,
      }) as Record<string, unknown>,
      ...(existing?.createdAt ? { createdAt: existing.createdAt } : {}),
    });
    storedSignals.push(stored);
  }

  for (const signal of listSystemImprovementSignals({ source: 'user-story-gap' }).filter(isStoryTopCandidateSignal)) {
    if (activeSignalIds.has(signal.id)) continue;
    deactivateSignal(signal, batchId, generatedAt);
  }

  return { count: storedSignals.length, signals: storedSignals };
}
